名称：建立MT7621

于：
  发布：
    类型：[已发布]
＃   推送：
＃     标签：
＃     -'v *'
  ＃个   分支：
  ＃     -大师
  时间表：
    - 的cron：0 17 * * 4
＃   观看：
   ＃类型：[开始]

职位：
  建立：
    运行：ubuntu-18.04

    步骤：
    - 名称：结帐
      用途：actions / checkout @ master
    - 名称：初始化环境
      env：
        DEBIAN_FRONTEND：非互动
      运行：|
        #sudo apt-get更新
        sudo apt-get -y install解压缩libtool-bin curl cmake gperf gawk flex野牛nano xxd \
        cpio git python-docutils gettext automake自动指向texinfo建立基本的help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
    - 名称：克隆的源代码
      运行：|
        cd工具链
        mkdir -p工具链-3.4.x
        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
        tar -xvf mipsel-linux-uclibc.tar.xz -C工具链-3.4.x
        mkdir -p / opt / images /
    - 名称：构建固件
      env：
        TNAME：“ K2P-5.0 K2P-USB-5.0 JCG-836PRO-5.0 JCG-AC860M-5.0 DIR-878-5.0 DIR-882-5.0 WR1200JS MI-R3G NEWIFI3 ”
      运行：|
        cwd =`pwd`
        CONFIG_TOOLCHAIN_DIR = $ {cwd // \ // \\\\ /} \\ / toolchain-mipsel
        cd中继
        在$ TNAME中为m；
        做
        如果[！-f configs / templates / $ m.config]; 然后
        回声“未找到configs / templates / $ m.config”
        1号出口
        科幻
        cp -f configs / templates / $ m.config .config
        ################################################ ##################################
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_MENTOHUST / d'.config＃删除配置项MENTOHUST
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT / d'.config＃删除配置项SCUTCLIENT
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS / d'.config＃删除配置项SS plus +
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_SSSERVER / d'.config＃删除配置项SS服务器
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER / d'.config＃删除配置项DNSFORWARDER
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_ADBYBY / d'.config＃删除配置项adbyby plus +
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_FRPC / d'.config＃删除配置项adbyby +
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_FRPS / d'.config＃删除配置项adbyby +
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_TUNSAFE / d'.config＃删除配置项adbyby +
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_ALIDDNS / d'.config＃删除配置项阿里DDNS
        sed -i'/ CONFIG_FIRMWARE_INCLUDE_SMARTDNS / d'.config
        ################################################ ####################
        echo“ CONFIG_FIRMWARE_INCLUDE_MENTOHUST = n” >> .config #MENTOHUST
        回声“ CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT = n” >> .config #SCUTCLIENT
        echo“ CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS = y” >> .config #SS plus +
        echo“ CONFIG_FIRMWARE_INCLUDE_SSSERVER = n” >> .config #SS服务器
        echo“ CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER = n” >> .config #DNSFORWARDER
        echo“ CONFIG_FIRMWARE_INCLUDE_ADBYBY = y” >> .config #adbyby plus +
        echo“ CONFIG_FIRMWARE_INCLUDE_FRPC = n” >> .config＃内网穿透FRPC
        echo“ CONFIG_FIRMWARE_INCLUDE_FRPS = n” >> .config＃内网穿透FRPS
        回声“ CONFIG_FIRMWARE_INCLUDE_TUNSAFE = n” >> .config #TUNSAFE
        echo“ CONFIG_FIRMWARE_INCLUDE_ALIDDNS = y” >> .config＃阿里DDNS
        回声“ CONFIG_FIRMWARE_INCLUDE_SMARTDNS = y” >> .config
        ################################################ #################################
        sed -i“ s / ^ CONFIG_TOOLCHAIN_DIR =。* $ / CONFIG_TOOLCHAIN_DIR = $ {CONFIG_TOOLCHAIN_DIR} / g” .config
        须藤./clear_tree_simple
        须藤./build_firmware_bkye $ m
        须藤MV -f images / *。trx / opt / images /
        完成
    - 名称：上传要发布的二进制文件
      用途：svenstaro / upload-release-action @ v1-release
      与：
        repo_token：$ {{ secrets.R_TOKEN }}
        文件：/ opt / images / *。trx
        标签：AtuoBuild
        覆盖：true
        file_glob：true
    - 用途：ncipollo / release-action @ v1
      与：
       bodyFile：“ changelog.md ”
       标签：AtuoBuild
       allowUpdates：true
       名称：Padavan固件
       令牌：$ {{secrets.R_TOKEN}}
